#ced_api_homepage:
#    path:     /
#    defaults: { _controller: CEDApiBundle:Default:index }

api_savevideo:
    path: /api/save_video
    defaults: { _controller: CEDApiBundle:Api:saveVideo }

api_getvideos:
    path: /api/get_videos
    defaults: { _controller: CEDApiBundle:Api:getVideos }
